variables:
  GIT_DEPTH: "0"
  GIT_SSH_COMMAND: "ssh -v" # Add verbose SSH output

github-sync:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Add debug output for the key file
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
    - echo "$GITHUB_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ls -la ~/.ssh/id_rsa # Check file permissions
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    # Test SSH connection
    - ssh -T -v git@github.com || true
  script:
    - git remote add github git@github.com:NicoZela23/raymi-landing.git
    - git fetch github
    - git push -f github HEAD:main
