variables:
  GIT_DEPTH: "0"

github-sync:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Write key explicitly with newlines
    - |
      echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
      echo "$GITHUB_PRIVATE_KEY" >> ~/.ssh/id_rsa
      echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Test SSH connection before git operations
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    # Debug SSH connection
    - ssh -Tv git@github.com || true
  script:
    - git remote add github git@github.com:NicoZela23/raymi-landing.git
    - git fetch github
    - git push -f github HEAD:main
